name: Build and Push Docker Images

on:
  push:
    branches:
      - main
    paths:
      - 'apps/next-app/**' # Trigger for Next.js app changes
      - 'apps/nest-app/**' # Trigger for Nest.js app changes
      - 'package/**'       # Trigger for updates in the package folder
      - '!*apps/**'        # Trigger for any other file outside `apps/`

jobs:
  build-and-push-next:
    if: ${{ contains(github.event.head_commit.message, 'apps/next-app/') || contains(github.event.head_commit.message, 'package/') || !contains(github.event.head_commit.message, 'apps/') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Next.js Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/next-app:latest -f apps/next-app/Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/next-app:latest

  build-and-push-nest:
    if: ${{ contains(github.event.head_commit.message, 'apps/nest-app/') || contains(github.event.head_commit.message, 'package/') || !contains(github.event.head_commit.message, 'apps/') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Nest.js Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/nest-app:latest -f apps/nest-app/Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/nest-app:latest


name: Build and Push 

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          echo "Building and pushing image..."
          docker build -t ${{ secrets.DOCKER_USERNAME }}/next-app .
          docker push ${{ secrets.DOCKER_USERNAME }}/next-app
